// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RestCountriesApi.Migrations
{
    [DbContext(typeof(CountriesDbContext))]
    partial class CountriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Country", b =>
                {
                    b.Property<string>("Alpha3Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Capital")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Alpha3Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Country", b =>
                {
                    b.OwnsOne("Flags", "Flags", b1 =>
                        {
                            b1.Property<string>("CountryAlpha3Code")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Png")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Svg")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CountryAlpha3Code");

                            b1.ToTable("Countries");

                            b1.WithOwner()
                                .HasForeignKey("CountryAlpha3Code");
                        });

                    b.Navigation("Flags")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
